/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gustavo' at '5/7/16 5:58 PM' with Gradle 2.12
 *
 * @author gustavo, @date 5/7/16 5:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
